### ISSUE TITLE
Filter view optimization

### ISSUE THREAD

**Issue by ERussel** [yapstudios/YapDatabase#126]
Hello.

I want to implement the following idea. Let's imagine we have message objects which have user_id and timestamp fields. I want to display in UITableView last message for each user_id sorted by timestamp. Any idea how to implement this logic in more efficiently way?

I did the following:

1. Create YapDatabaseView grouping by user id and sorting by timestamp.
2. Created YapDatabaseViewMapping with fixed range, sorting groups by first message's timestamp.

The problem is this implementation works very slow when we have quick flow of incoming/outgoing messages. Any advise about this?

**Comment by robbiehanson** [comment]
There are several different ways to go about something like this.

First, consider what it is you're displaying in this "conversation" tableView. If it's like most messaging apps, then you have (per cell):
- User's display name
- Timestamp of most recent message
- First 1 or 2 lines of most recent message.

And thus there are a couple different ways to think about it. For example:
- This is a list of *users*, sorted by most recent associated message, and the cell includes message info
- This is a list of *messages*, sorted by timestamp, and the cell includes user's display name
- This is a list of *conversations*, sorted by timestamp

But before you decide which way to think about it, you need to also consider the UI requirements:
- If a user's display name changes, then the cell should update
- If a new message comes in for a conversation, then the cell should update
- If the most recent message is deleted, then the cell should update
- If the user deletes the conversation, then it should be easy to delete every associated message

The first 3 requirements are what I call "loose" requirements. (for lack of a better word). That is, they are not strict requirements in terms of purely the data model. They are really only requirements in terms of the UI. And thus they are perfect candidates for the YapDatabaseHooks extension.

That is, the YapDatabaseHooks extension allows one to write code to execute this UI specific "glue" code. For example, one could add code that logically says"
- "if a user.displayName property is changed, then touch whatever object is needed in order to ensure the tableView will re-draw the correct cell"
- "if the most recent message in a conversation changes, then touch whatever object is needed in order to ensure the tableView will re-draw the correct cell"

For this situation, I generally recommend a dedicated Conversation object.
That is, you'd have the following object types:
- MYUser
- MYConversation
- MYMessage

Further:
MYUser.collection = "users"
MYUser.key = userID

MYConversation.collection = userID
MYConversation.key = conversationID

MYMessage.collection = conversationID
MYMessage.key = messageID

Which means that deleting all messages in a conversation is as easy as saying removeAllObjectsInCollection:conversationID. And it's always easy to "walk the tree" ( message -> conversation -> user ). You could simplify even further if you store a MYMessage.userID property.

I hope this helps.

**Comment by ERussel** [comment]
Hello, Robbie

Thanks for this full description. I will try this idea.
