### ISSUE TITLE
Using Views in conjunction to Relationship?

### ISSUE THREAD

**Issue by shsteven** [yapstudios/YapDatabase#129]
Is there any way to use the View extension together with the Relationship?

e.g. 

    YapDatabaseViewGroupingWithObjectBlock groupingBlock = ^NSString *(NSString *collection, NSString *key, Model *object, YapDatabaseRelationshipEdge *edge) {
            // perform grouping based on edges
            return nil;
        };

**Comment by jordanhamill** [comment]
:+1:

**Comment by robbiehanson** [comment]
This is now possible.

In v2.7, the YapDatabaseReadTransaction is a parameter to the groupingBlock. (and the sortingBlock) So you'll be able to query the relationship extension to make decisions.

**Important Note**: YapDatabase notifies extensions (of changes to the database) in a particular order. It uses the order in which the extensions were registered. This is important to understand because, if you want your View extension to rely upon your Relationship extension, then what you're saying is that you want the Relationship extension to process changes FIRST, before your View extension process changes (and invokes your groupingBlock). In other words, you want your Relationship extension to be up-to-date by the time your groupingBlock code runs. Thus, you need to ensure that you register your Relationship extension BEFORE registering your View extension.

**Comment by shsteven** [comment]
@robbiehanson wonderful! it just keeps getting better!
