### ISSUE TITLE
YapDatabaseFilteredView when the view controller shows up

### ISSUE THREAD

**Issue by nebiros** [yapstudios/YapDatabase#141]
I have a tabbed app. First tab has a view grouped by the first letter of the contact name. The second tab has a view, a YapDatabaseFilteredView which is initialised using the view registered in the first tab. My problem is that when I change something in the first tab is reflected in the second tab but when I open the second tab whiteout doing nothing in the first one the YapDatabaseViewFiltering block isn't executed at all. 

My code:

Tab 1 table view controller: https://gist.github.com/nebiros/026597f2230ec135b375
Tab 2 table view controller: https://gist.github.com/nebiros/3d0b985d9b4d66be5339

I don't know what I'm doing wrong, if you look at the commented code I try a lot of stuff. I don't know if I need to created the view from the first tab again?. Thank you in advance.

**Comment by robbiehanson** [comment]
I see method named 'tht_setupDatabase' that is called in viewDidLoad from both viewControllers, but I don't see the method implementation anywhere.

One possible problem (and I'm guessing here because I'd need to see how you setup each 'databaseForegroundConnection'):

If 'self.databaseForegroundConnection' is the same YapDatabaseConnection instance (being shared between 2 viewControllers), then you may be "eating" the change-sets in one viewController, which prevents the other from seeing it. In other words:

Say you have a single YapDatabaseConnection instance being shared by 2 viewControllers in a manner similar to the gists you posted. Then you perform an asyncReadWriteTransaction, and modify the database. After this commit completes, it will post a YapDatabaseModifiedNotification, which will be received by both view controllers. However, one of the viewControllers will receive the notification first. And when it does, it promptly performs the following code:

```obj-c
- (void)yapDatabaseModified:(NSNotification *)notification
{
    // "Eat" the change-sets
    NSArray *notifications = [self.databaseForegroundConnection beginLongLivedReadTransaction];
```

So when the second viewController runs its yapDatabaseModified method, it will end up with a notifications array that's empty. (Because it's already at the very latest commit.)

Like I mentioned earlier, without seeing how the database connections are setup, I'm just blindly guessing at this point. But if this is the problem, then you have 2 options:

- Use separate YapDatabaseConnection instances
- Share the main-thread YapDatabaseConnection safely. See this wiki article: https://github.com/yapstudios/YapDatabase/wiki/Performance-Pro#sharing_the_ui_databaseconnection

Let me know.

**Comment by nebiros** [comment]
Hey @robbiehanson, thank for your help. I ended up with this:

Each time a notification is fired, I just update mappings for each view controller. I was reading about it, and seems `[tableView reloadData]` is pretty cheap, because it just re-render the cells that are shown, I change the way that I was creating the database and also the views, I move all this code to the `AppDelegete`, so, when the user start the app I create the database, the views, etc.. I'm sharing the database connection, yes. I'll paste you how I resolved it, I'm using a FilteredView and the FTS extension.

Application delegate: https://gist.github.com/nebiros/36a4be9fe9f5aff34a99
Tab 1 table view controller: https://gist.github.com/nebiros/b690f4651942ab31835f
Tab 2 table view controller: https://gist.github.com/nebiros/42e37f1f31c99b05e12c
Database helper: https://gist.github.com/nebiros/0aa01734a45e916ad6c6
View controller category to initialise the connections: https://gist.github.com/nebiros/b8a6be53c5446d2416e1

Thank you.

**Comment by robbiehanson** [comment]
Glad you got it working. Let me know if you have any other questions.
