### ISSUE TITLE
I don't know when the query is finished.

### ISSUE THREAD

**Issue by truonguit2010** [yapstudios/YapDatabase#155]
Hi,
I implement query using SecondaryIndex. But I don't know when it finish query. I will store all my object to an array. When I finish the query I return all one time.

Here is my codes:
[tran enumerateKeysAndObjectsMatchingQuery:query usingBlock:^(NSString *collection, NSString *key, id object, BOOL *stop) {
            [stores addObject:object];
            if (stop == YES) {
                result(stores);
            }
            NSLog(@"Get my store collection: %@ - key: %@", collection, key);
        }];
Thank you.

**Comment by robbiehanson** [comment]
The ```BOOL *stop``` parameter is a standard parameter that allows one to bail out of a loop. For example, if you were enumerating items in an array, looking for something, you might write it like this:

```objective-c
id objectImLookingFor = nil;
for (id object in myArray) {
    if ([object isWhatImLookingFor]) {
        objectImLookingFor = object;
        break;
    }
}
```

So the ```break``` keyword allows one to break out of the loop. But you can't use break in a block. So you have to do something different. For example:

```objective-c
__block id objectImLookingFor = nil;
[myArray enumerateObjectsUsingBlock:^(id obj, NSUInteger idx, BOOL *stop){
    if ([object isWhatImLookingFor]) {
        objectImLookingFor = object;
        *stop = YES;
    }
}];
```

The YapDatabase API uses the same ```BOOL *stop``` standard that Apple uses. So you'd write your code like this (since you don't need to break out of the loop):

```objective-c
[tran enumerateKeysAndObjectsMatchingQuery:query usingBlock:
    ^(NSString *collection, NSString *key, id object, BOOL *stop) {
    [stores addObject:object];
}];
// Done with query - all objects are in stores array
```
