### ISSUE TITLE
iOS Extensions require shared-file support

### ISSUE THREAD

**Issue by dhennessy** [yapstudios/YapDatabase#160]
iOS extensions like Today Widgets or WatchKit Apps operate in a different process space to the main app.  YapDatabase doesn't currently work well in this environment because there's no support for accessing a shared database file. 

This causes problems even if the extension is only reading the database - the instance of YapDatabase in the extension won't notice changes made to the underlying database by the main app, and so won't be displaying the correct data.

It seems to me that there are 2 approaches to extending YapDatabase to support shared-file databases:

## Detect file changes, rebuild connections

1. Observe the underlying database file to detect when a different process changes it.
2. Broadcast a 'ExternalDatabaseChangeDetected' notification
3. All objects that cache database-related state (such as connections) set a special 'InvalidState' flag which causes future API calls to fail.
4. The YapDatabase instance is removed from the YapDatabaseManager open database list.
5. The client app uses the notification to re-create any database / connection / extension objects
6. The client app refreshes its UI

## Support SQLITE file locking, detect changes

1. Observe the underlying database file to detect when a different process changes it.
2. When a change is detected, re-read the snapshot number. If it's changed, then treat it as a change notification.
3. When a write transaction is making a change, obtain an exclusive lock on the file (and deal with busy-wait).
4. Since the file change detection is often asychronous, also detect changes by doing a snapshot update with the expected existing value: (execute `UPDATE yap2 SET data = '47' WHERE extension = '' AND key = 'snapshot' AND data = '46'` and verify that number of rows changed were 1)

Although the first option is potentially simpler, it would have some pretty horrible performance characteristics. The second option seems the right thing to do. Before I dig in and start work, I'd love some feedback about whether this seems a good approach?

**Comment by robbiehanson** [comment]
There are 2 main problems (that I’m currently aware of):

- YapDatabase uses dispatch_queue’s to ensure only a single writer at a time.

That is, sqlite only supports a single writer at a time. And YapDatabase enforces this through a technique of it’s own (within it’s own process). In other words, YapDatabase isn’t currently setup to handle the possibility that process A cannot acquire the sqlite write lock because process B has it. Thus, this support will have to be added.

I believe this can be handled properly via the sqlite busy handler.

- YapDatabase uses an internal change-set mechanism it uses to announce changes to the database (and to keep the caches up-to-date)

This change-set mechanism needs to be expanded to go across processes. That is, via inter-process communication. Thus if processB receives a change-set from processA, then it can process it as if the change-set came from a different connection within it's own process. (That is, using the current architecture.) However, if processB doesn't receive the change-set from processA in time, then it simply needs to flush it's caches. This particular edge case may have other consequences in terms of the YapDatabaseModifiedNotification (which we may be forced to broadcast without knowing what changes took place in commit 33, for example)

**Comment by dhennessy** [comment]
It looks like these are perhaps independent enhancement requests: 

1. Adding support for busy-wait on the sqlite write lock will enable extensions to write to the database. Right now, iOS extensions using YapDatabase can only read the data (and even then risk the data being out-of-date).

2. Adding an API to nuke the caches relating to a database would allow an app or extension using YapDatabase to ensure that it was displaying the correct data. The instance can decide when to invoke the API (e.g. an app could do it when it becomes active, a today extension could do it in `widgetPerformUpdateWithCompletionHandler:`, etc.)

Right now, using IPC to coordinate change-set updates isn't feasible on iOS. WatchKit extensions don't support background execution modes. The only 'blessed' data sharing options seems to be NSUserDefaults and shared files in a common app group (see https://developer.apple.com/library/ios/technotes/tn2408/_index.html).

**Comment by robbiehanson** [comment]
> Right now, using IPC to coordinate change-set updates isn't feasible on iOS.

Not entirely true. Some research turned up some cool stuff:
https://devforums.apple.com/message/1078581#1078581
https://devforums.apple.com/thread/256667?tstart=0
https://github.com/mutualmobile/MMWormhole

Basically, CFNotificationCenterGetDarwinNotifyCenter / notify.h will work, and will allow one process to notify another that a commit has been made.

**Comment by dhennessy** [comment]
That's interesting. I wonder what performance / timing implications are associated with those mechanisms.

I have a feeling the most robust solution would be to assume that the IPC mechanisms are potentially used to maintain the cache, but the core engine would still have to deal with the situation that when a transaction begins, the underlying database data may have changed. The big question from an API perspective is whether or not to fail the transaction call at that point (since the second process might be about to overwrite changes made by the first process).

**Comment by robbiehanson** [comment]
> the core engine would still have to deal with the situation that when a transaction begins, the underlying database data may have changed

Correct, but this is already supported. Meaning there's never a reason to fail the transaction call (for this purpose).

A quick overview on some of the architecture internals:

YapDatabase uses a combination of snapshots and changesets in order to keep its caches up-to-date. The snapshot mechanism is straight-forward. Within sqlite we keep a table named "yap2" which is responsible for storing a bunch of metadata. One of the rows in this table is named "snapshot", and it stores a uint64_t. This value is incremented every-time a readWriteTransaction occurs (in which the database is actually modified).

So when a read-only transaction begins, it starts by reading this snapshot value from the database. (There are some optimizations I'm going to gloss over right now. But they won't apply to a database being used by multiple processes. So they're not worth discussing here anyway.) If the read-only transaction discovers the snapshot on disk is "what it expects", then it need do nothing (its caches are already up-to-date). But if the transaction discovers a snapshot on disk that is different, then it performs a "fast-forward" operation. And this is where the changesets come in.

Immediately prior to performing a commit, a read-write transaction registers a "changeset" with the database system. The changeset is basically a record of all the changes being made by the commit. For example, it has a list of rowids that were deleted, modified, etc. In fact, it's even more powerful than that, because the extensions can add their own custom information to the changeset too. So a view might add information specific to its needs. That is, information that enables other connections to more efficiently fast-forward their view-connection instance (without fully flushing their cache).

What's important to note here is that this changeset is registered before the commit is started. So one might have connection4 (on thread4) executing a readWrite commit (snapshot=61). And connection2 (on thread2) starting a read-only transaction. Depending on the timing, connection2 may or may not pick up that commit by connection4. In other words, it's either going to see snapshot 60 or 61. It it does read 61, then it simply asks the database for changeset 61, processes the changeset (aka updates its caches), and then proceeds with the read-only transaction.

So in order to support multiple processes, YapDatabase needs to be modified to support the possibility that a changeset (for some particular snapshot) isn't available, because the commit took place in a different process. This is actually very easy to do. It simply means that all the caches (and any other cached in-memory state) need to be flushed (from the database core, and any active extensions on that particular connection).

The hard part is answering questions for the user interface. Such as "did this collection/key change"? And in this multi-process scenario, the answer may now be "maybe...".  Or, another question from the UI, "what are the rowChanges & sectionChanges for my tableView"? And the answer is "I don't know, you should probably do a reload..."

**Comment by dhennessy** [comment]
It looks like Realm went through some similar issues:

https://github.com/realm/realm-cocoa/issues/824

**Comment by jeremiegirault** [comment]
FYI, as a user we had to remove Yap due to the multi-process lack. However, the simple version about "doing a reload" would have been good enough for our use case. (plus computing a changeset is quite hard)
The cross-process notification could be simply done with libnotify (I noticed that it is mostly good enough).
(Realm is using a low-level named pipe: https://realm.io/news/thomas-goyne-fast-inter-process-communication/)
BTW exception made on this small thing Yap is awesome, thanks.

**Comment by jeremiegirault** [comment]
@robbiehanson If I wanted to add basic IPC support to yap where should I start ? 
- SQL Open flags ?
- I know how to notify cross-process, when / how should it happen ?

Thanks

**Comment by maelp** [comment]
@robbiehanson would this work:

 - use `busy_handler` to acquire database write lock on different processes
 - if we miss a changeset for a given transaction increase, we assume the changeset has been updated on another process, and we flush all caches (in practice, I guess extensions update the database sufficiently rarely that it should not be an issue)

What I'm not sure about:

 - how to sync the initial snapshot number at the start of the app
 - how to update `YapDatabaseModifiedNotification` so it works correctly

**Comment by robbiehanson** [comment]
This feature has been implemented, and is included as of v2.9
