### ISSUE TITLE
init method not found in last version

### ISSUE THREAD

**Issue by Danyaga** [yapstudios/YapDatabase#174]
Hi. I have just updated my pods (YapDatabase version 2.5.2) and i have a issue with YapDatabaseView's init, in particular my code is:

YapDatabaseView *databaseView = [[YapDatabaseView alloc] initWithGroupingBlock:groupingBlock
                                                                 groupingBlockType:groupingBlockType
                                                                      sortingBlock:sortingBlock
                                                                  sortingBlockType:sortingBlockType
                                                                        versionTag:DATABASE_VERSION];

The Xcode error is pretty easy: It is not be able to find method. This method has been removed in this version? How can i fix it?

**Comment by Danyaga** [comment]
The answer is the following:
    YapDatabaseViewGrouping * grouping = [YapDatabaseViewGrouping withObjectBlock:groupingBlock];
    YapDatabaseViewSorting * sorting = [YapDatabaseViewSorting withObjectBlock:sortingBlock];;
    
    YapDatabaseView *databaseView = [[YapDatabaseView alloc] initWithGrouping:grouping sorting:sorting versionTag:DATABASE_VERSION];

**Comment by robbiehanson** [comment]
Hey Danyaga, glad you found the solution.

Yeah, quite a few people have been bit recently by some of the code that was removed. (Including myself ! ) Which caught me rather off guard, because I marked all these methods as deprecated within the code some time ago:

```objective-c
- (id)initWithGroupingBlock:(YapDatabaseViewGroupingBlock)groupingBlock
          groupingBlockType:(YapDatabaseViewBlockType)groupingBlockType
               sortingBlock:(YapDatabaseViewSortingBlock)sortingBlock
           sortingBlockType:(YapDatabaseViewBlockType)sortingBlockType
                 versionTag:(NSString *)versionTag
__attribute((deprecated("Use method initWithGrouping:sorting:versionTag: instead")));
```

Normally this works fine. Except I wasn't seeing the deprecation warnings in Xcode. I'm guessing you weren't either. So... either I screwed up (improper attribute usage ?), or it was an Xcode bug. Not really sure which ...
