### ISSUE TITLE
how to disable CocoaLumberjack

### ISSUE THREAD

**Issue by xinwo** [yapstudios/YapDatabase#179]
Hi

after 
pod 'YapDatabase'
pod update

CocoaLumberjack will be installed automatically.
How can I disable it, because CocoaLumberjack conflicts with another library in my project.

**Comment by robbiehanson** [comment]
Does the other library require CocoaLumberjack v2.0 or later ?

**Comment by raw1z** [comment]
I am facing the same issue and yes the other library requires CocoaLumberjack v2.0.

**Comment by chrisballinger** [comment]
I feel like the problem is more rooted in the fact that CocoaLumberjack 2.0 doesn't have a clear upgrade path from 1.9. The best solution would probably be to include some deprecated 1.9 behavior in 2.0 to allow people to more easily transition. There are a lot of libraries that depend on 1.9 and as soon as one of them moves to 2.0 there is a very messy situation. :-\

**Comment by xinwo** [comment]
I found out a work around, by not using pod to install YapDatabase, but to use submodule.
Then by defining "YapDatabaseLoggingTechnique=0", I can get rid of CocoaLumberjack.

**Comment by robbiehanson** [comment]
@xinwo is referring to issue #182

**Comment by robbiehanson** [comment]
Related: Issue #188

**Comment by robbiehanson** [comment]
YapDatabase v2.7 will use CocoaLumberjack 2.0+

If you need CocoaLumberjack 2.0 now, you can use the 2.7 branch.
