### ISSUE TITLE
Replacing .sqlite files, and flushing connections does not do anything without restarting app

### ISSUE THREAD

**Issue by benrosen78** [yapstudios/YapDatabase#189]
In my app, I implemented a sync with Dropbox. In restoring the database files from a Dropbox backup, I replace the database files (.sqlite). Then I run this code: 

    YapDatabaseConnection *logsDatabaseConnection = [_logsDatabase newConnection];
    [logsDatabaseConnection flushMemoryWithFlags:YapDatabaseConnectionFlushMemoryFlags_All];

    YapDatabaseConnection *songsDatabaseConnection = [_songsDatabase newConnection];
    [songsDatabaseConnection flushMemoryWithFlags:YapDatabaseConnectionFlushMemoryFlags_All];
    
    _repertoiresDatabase = [[YapDatabase alloc] initWithPath:_repertoiresDatabasePath];
    _songsDatabase = [[YapDatabase alloc] initWithPath:_songsDatabasePath];
    _logsDatabase = [[YapDatabase alloc] initWithPath:_logsDatabasePath];

Even after this, I have to restart the app for transactions to have the new database. How can I fix this?

**Comment by robbiehanson** [comment]
I'm not sure I fully understand the question.

```objective-c
YapDatabaseConnection *logsDatabaseConnection = [_logsDatabase newConnection];
[logsDatabaseConnection flushMemoryWithFlags:YapDatabaseConnectionFlushMemoryFlags_All];
```

There's no need to execute flushMemoryWithFlags here. That method is designed to remove cached information from a connection. That is, to free up memory, especially in low-memory situations. For example, say you have a connect that's been open for some time, and has accumulated several objects within its internal cache. You could run the flushMemoryWithFlags method to tell the connection to remove all items from its cache (in order to free up memory).

> Even after this, I have to restart the app for transactions to have the new database. How can I fix this?

How are you doing the syncing with dropbox? You're not expecting dropbox to properly sync the entire database file are you?

**Comment by benrosen78** [comment]
Hi Robbie,
In my code, I restore the .sqlite file from dropbox and replace the old .sqlite file with it. Once I do that, the transactions I make with the database still show the old database. Then, when I restart the app fully it shows the new database, the one that I put there. I would like to figure out how I can make it not require a restart of the app. I'm not sure if it is clearing cache, or what I have to do to fix it?

**Comment by robbiehanson** [comment]
Do you alloc/init the YapDatabase instance before or after you're restored the .sqlite file from dropbox?

**Comment by benrosen78** [comment]
After.

**Comment by robbiehanson** [comment]
On theory:

SQLite writes the transaction data (from a readWriteTransaction) first to a Write-Ahead Log (WAL) file. The records in the WAL act as an override for what's in the sqlite file. So a sqlite connection will first check the WAL to see if the desired page is there. If so, it will use the page from the WAL. Otherwise, it will read the page from the sqlite file.

This is explained in more depth here: https://www.sqlite.org/wal.html

But what I'm getting at is this: It's possible that if you're only syncing the sqlite file, then you're missing some recent transactions. Because these are not in the sqlite file yet. There are instead in the WAL, and have yet to be check-pointed into the sqlite file.

Is it possible this is related to the issue you're seeing ?

**Comment by benrosen78** [comment]
I don't think so. My reason for that being all the data is there and you just have to restart the app for the new database to show. I only sync the .sqlite file and all the recent transactions show except you have to restart the app for anything and everything to show.

**Comment by robbiehanson** [comment]
> Do you alloc/init the YapDatabase instance before or after you're restored the .sqlite file from dropbox?

In your code example you demonstrate creating a new YapDatabaseConnection instance. Notice that I am instead asking about the YapDatabase instance. Is this created before or after you've completed copied over the updated *.sqlite file ?

**Comment by benrosen78** [comment]
As you can clearly see in my code, I alloc/init my 3 databases after I restored the updated .sqlite files.

**Comment by robbiehanson** [comment]
I was a bit confused by the code snippet because:

```objective-c
/*1*/ YapDatabaseConnection *logsDatabaseConnection = [_logsDatabase newConnection];
/*2*/ [logsDatabaseConnection flushMemoryWithFlags:YapDatabaseConnectionFlushMemoryFlags_All];

/*3*/ YapDatabaseConnection *songsDatabaseConnection = [_songsDatabase newConnection];
/*4*/ [songsDatabaseConnection flushMemoryWithFlags:YapDatabaseConnectionFlushMemoryFlags_All];

/*5*/ _repertoiresDatabase = [[YapDatabase alloc] initWithPath:_repertoiresDatabasePath];
/*6*/ _songsDatabase = [[YapDatabase alloc] initWithPath:_songsDatabasePath];
/*7*/ _logsDatabase = [[YapDatabase alloc] initWithPath:_logsDatabasePath];
```

On line 1, you reference the _logsDatabase instance. But you apparently don't init _logsDatabase instance until line 7.

So either logsDatabaseConnection is nil, or _logsDatabase was alloc/init'd earlier. And line 7 is attempting to re-create it.

**Comment by benrosen78** [comment]
So, what happens is I have `PIDatabaseController`, a singleton class used to manage all the databases and all the functions we have to do with them. 
In settings, when the user restores from Dropbox, I run that code. After the new database has been placed in the file system, I alloc/init the databases AGAIN (lines 5-7). So, I am alloc/init'ing the databases twice: once pretty much when the app starts, and one when they restore from a backup, after the new files have been placed in the file system.

**Comment by robbiehanson** [comment]
Ah, gotcha. That makes sense. Now we're getting to the crux of the problem I think.

So, when a YapDatabase instance is alloc/init'd, it opens its own internal "connection". It's not actually a YapDatabaseConnection, but it is a ```sqlite*``` instance. Which means that it has an open file descriptor for the database file. (This internal sqlite instance is first used for initialize & prepare the database. And then it is kept around to perform checkpoint operations.)

So I think the problem we're seeing is that you're trying to replace a file that is currently open by the application process. I'm not 100% sure exactly how the operating system treats this. But perhaps the end result is what we're seeing - the dropbox version of the file isn't visible until the process restarts.

A couple ideas:

1. Don't alloc/init the YapDatabase instance until after you've completed the Dropbox sync.

or perhaps:

2. When you get the updated file from Dropbox, then you'll need to:
- kill all YapDatabase & YapDatabaseConnection instances
- Wait for the YapDatabaseClosedNotification
- Then replace the .sqlite file
- And then alloc/init the database instance(s) again

However, in the implementation of solution two, you still run into the edge-case where a code path wants to do something with YapDatabase, but there isn't a YapDatabase instance available. Which is why I'd suggest solution number one.

**Comment by benrosen78** [comment]
Thank you! Fixed.

**Comment by robbiehanson** [comment]
Sweet ! Glad we got to the bottom of this.
