### ISSUE TITLE
Is it safe to share the YapDatabase file between iOS and OS X ?

### ISSUE THREAD

**Issue by zubko** [yapstudios/YapDatabase#190]
I want to make an utility generator app running on Mac which will make the starting DB with default data and settings for the iOS app.

If I avoid using NS classes which aren't on iOS, it should be safe otherwise, right?

**Comment by robbiehanson** [comment]
Yes, the *.sqlite file is compatible between platforms, so you can simply copy it from your Mac into your iOS bundle. (I know several other developers who have done exactly what you're mentioning.)

There's only one thing to watch out for (if you're not already aware of it):

YapDatabase uses SQLite in WAL (Write-Ahead Log) mode. This means that SQLite will first write the transaction to a WAL file. And it will later sync the contents of the WAL file into the actual sqlite file. This is called performing a checkpoint. And YapDatabase will automatically perform the checkpoint as soon as possible. So, long story short:

In your generator app (if you're using YapDatabase to populate a sqlite file), I would give the app a few extra seconds to finish completing the checkpoint. (Otherwise you may end up with 1 or more commits sitting in your WAL file instead of in your *.sqlite file.)

Let me know if you have any other questions.

**Comment by zubko** [comment]
Thanks for confirmation. That's a good point about WAL, I was going to copy all the generated files, if it can work with just copying sqlite file, that will be even better.

**Comment by zubko** [comment]
There is one quite funny moment which I missed for being new to Swift, but because of namespacing the same classes in 2 applications have different names. Like for example generated one will be "Generator.User" and in the app it will be "ApplicationName.User", so NSKeyedArchiver will fail to unarchive them. 
I'm thinking of either to use a little bit of Objective-C for serialization purposes or maybe switching to JSON or FastCoding instead of NSKeyedArchiver.
