### ISSUE TITLE
YapDatabaseViewGrouping.withKeyBlock({}) never executed

### ISSUE THREAD

**Issue by wahyusumartha** [yapstudios/YapDatabase#191]
I found a problem when trying to setting up yapdatabase with swift, 

here is my code 

    private func databasePath() -> String {
        let paths = NSSearchPathForDirectoriesInDomains(NSSearchPathDirectory.DocumentDirectory,
            NSSearchPathDomainMask.UserDomainMask,
            true)
        let baseDir = (paths.count>0) ? (paths[0] as! String) : (NSTemporaryDirectory() as String)
        let databaseName = "EtsuriOfflineCache.sqlite"
        return baseDir.stringByAppendingPathComponent(databaseName)
    }
    
    func setupDatabase() {
        let databasePath = self.databasePath()
        
        // create the database 
        println("Creating database instance...")
        self.database = YapDatabase(path: databasePath)
        
        // creating view 
        println("Creating view...")
        var grouping = YapDatabaseViewGrouping.withKeyBlock({ (collection: String!,
            key: String!) -> String! in
            return "all"
        })
              
        var sorting = YapDatabaseViewSorting.withObjectBlock({
            (group: String!, collection1: String!, key1: String!, obj1: AnyObject!,
            collection2: String!, key2: String!, obj2: AnyObject!) -> NSComparisonResult in
                            return NSComparisonResult.OrderedDescending
            } as! YapDatabaseViewSortingWithObjectBlock)
        
        let view = YapDatabaseView(grouping: grouping, sorting: sorting, versionTag: "1", options: nil)
        if self.database?.registerExtension(view, withName: "order") == false {
            println("Unable to register extension: order")
        }
    }

when i call setupDatabase() function the block inside sorting and grouping variables never executed, 

Thanks,

**Comment by robbiehanson** [comment]
A YapDatabaseView instance acts like a persistent query. It operates on the collection/key/object/metadata rows that are in the database. However, if there are zero rows in the database, then the view instance doesn't have any work to do, and thus won't invoke your grouping/sorting blocks.

Also, keep in mind that the instance is persistent. For example, let's say you have a database with 5 rows. Then you instantiate a YapDatabaseView instance for the first time ever. When you first run the app, the YapDatabaseView instance will need to process those 5 rows. So your grouping/sorting block will be invoked. However, because YapDatabaseView is persistent (by default), it then stores the result of all its work within the sqlite database. (In a separate table within sqlite.) Thus, if you launch the app a second time, the YapDatabaseView won't need to re-process those 5 rows, and thus your grouping/sorting block won't be invoked again. YapDatabaseView will only invoke your grouping/sorting block again if:
- you insert a new row
- you modify an existing row
- you change the versionTag (which tells YapDatabaseView that the grouping/sorting blocks have changed since the last launch, and it should re-populate itself)

Let me know if you have any other questions.

**Comment by robbiehanson** [comment]
Closing this issue since I haven't heard back from you.

Let me know if you still have questions, or if you're still experiencing problems, and I'll happily re-open the issue.
