### ISSUE TITLE
crash at "YapDatabaseTransaction.m, serializedObject = connection->database->objectSerializer(collection, key, object);" when using xcode7

### ISSUE THREAD

**Issue by xinwo** [yapstudios/YapDatabase#218]
after compiling my code with xcode7(ios9 sdk), app will crash when yap tries to write data.
any solution?

**Comment by robbiehanson** [comment]
It looks like the objectSerializer block is throwing an exception.

If you're using the default serializer, then perhaps the object you're attempting to write to the database doesn't support NSCoding.

This wiki article should help:
https://github.com/yapstudios/YapDatabase/wiki/Storing-Objects

**Comment by robbiehanson** [comment]
Let me know if you have any other questions. Or if we need to re-open this issue.

**Comment by xinwo** [comment]
Hi, 

Thank you.

I'm using
YapDatabase.propertyListSerializer()
and, the object I pass to it is a String(json format)
Any idea why it crashes?

**Comment by xinwo** [comment]
changing to defaultDeserializer solved the problem.

**Comment by robbiehanson** [comment]
> I'll appreciate if someone can tell me why

The propertyListSerializer is for encoding objects using Apple's "Property List" format:
https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/PropertyLists/Introduction/Introduction.html

Since Apple makes heavy use of the property list format for a number of things, they've done a good job making property lists very fast. And thus, some people prefer to use the property list format for storage of simple data.

The catch, concerning the property list format, is that it only supports a few basic types. And it does NOT support custom types. This means that you can only use it for really basic data structures (think dictionaries, strings, and numbers).

If you were previously using the propertyListSerializer, and you were getting a crash, then it's likely you were trying to serialize a data type that's not supported by the property list format. To test this theory, you can try manually serializing your objects using the same code that's within the propertyListSerializer. I believe you'll see it throw an exception.

> the object I pass to it is a String(json format)

Perhaps what you thought was a string was actually something else at runtime? The only way to know for sure is to catch the exception, and see what the NSPropertyListSerialization class is complaining about.

> changing to defaultDeserializer solved the problem

Your serializer & deserializer need to match. You shouldn't use a propertyListSerializer and the defaultDeserializer together. If you're currently configured this way, and it's working, I'm surprised.

**Comment by robbiehanson** [comment]
One other thing that may be worth mentioning:

YapDatabase put the responsibility of serialization & deserialization on your shoulders. This give you great flexibility, but at the cost of some responsibility.

Further, YapDatabase doesn't do anything magic concerning these serialized "blobs". That is, YapDatabase doesn't know what technique you used to serialize your data. And thus it can't magically deserialize it for you. What I'm getting at is this:

If you've been playing around with a bunch of different serialization techniques, then you need to keep in mind that you might now be in a situation where you have a sqlite database full of serialized blobs, serialized using different methods, that now require a bunch of different deserialization techniques. This is really bad. Because you'll have no way to know how to deserialize any given row in the database.

What you want is a consistent serialization & deserialization routine. It can be whatever you want. But it needs to remain consistent, and it needs to work for the objects you're putting into the database. So if you're in the development stage, and you've decided to switch from plist serialization to NSCoding (defaultSerializer & defaultDeserializer), then you should probably delete the sqlite database file. Remember: YapDatabase doesn't know if there are rows in the database that your deserializer won't be able to handle.

**Comment by xinwo** [comment]
Thank you for the detailed explanation.

The code worked well under XCode6(swift 1.2), and crashed after I changed it to XCode7(swift 2).
My only guess is some changes about swift lead to the crash. But I can't figure out what it is.

> the object I pass to it is a String(json format)

I set a break point at 
>YapDatabaseTransaction.m, line 4385
serializedObject = connection->database->objectSerializer(collection, key, object);

and found out
1. neither of connection, connection->database, connection->database->objectSerializer is nil
2. the type of collection, key, object are NSTaggedPointerString *, NSTaggedPointerString *, __NSCFString * respectively
which means it should work, at least I think so.

Then the debugger won't take me any further.
I thought if I "step into" next step, the debugger would take me to
line 139 of YapDatabase.m
```
line: 136 + (YapDatabaseSerializer)propertyListSerializer
line: 137 {
line: 138 	return ^ NSData* (NSString __unused *collection, NSString __unused *key, id object){
line: 139 		return [NSPropertyListSerialization dataWithPropertyList:object
line: 140 		                                                  format:NSPropertyListBinaryFormat_v1_0
line: 141 		                                                 options:0
line: 142 		                                                   error:NULL];
line: 143 	};
line: 144 }
```
but it didn't, but only give me EXC_BAD_ACCESS.
Looks like one or all of connection, connection->database, connection->database->objectSerializer are released at some point before.
if it is so, I can't figure out why.

**Comment by robbiehanson** [comment]
> Which means it is the XCode7 compiler that causes the problem.
> I am not sure if it is XCode7's bug, but I'll fire a bug report to Apple.

Thanks for the heads up. Let us know what you find. If anyone else runs into the same problem, I'll direct them to this issue.

**Comment by jj0b** [comment]
I can confirm this issue. The only way I don't get the same crash as @xinwo is if I create the database with the `YapDatabase(path:)` method. Using the methods that let you specify the serializer and deserializer, at least when using the defaultSerializer and defaultDeserializer, or the propertyList equivalents result in this crash.
