### ISSUE TITLE
Aggregate queries over subset of rows

### ISSUE THREAD

**Issue by sbooth** [yapstudios/YapDatabase#230]
What is the proper way to perform an aggregate query over a subset of rows in a secondary index?  For example, given an array of object keys, how would one perform a `SUM` over an indexed property of those objects?

Here's a concrete example: a music library consists of tracks and playlists, and each playlist consists of a number of tracks.  It's possible using YDB's relationships to determine the object keys associated with the tracks in a playlist without having to actually load the tracks.  How would one compute the duration of the playlist (assuming duration is an indexed property on tracks) without resorting to loading all the tracks?

I've come up with something that works but it feels funny:

```
let query = YapDatabaseQuery(aggregateFunction: "SUM(duration)", string: "WHERE rowid IN (SELECT rowid FROM database2 WHERE key IN (?))", parameters: [trackUUIDs])
```

**Comment by robbiehanson** [comment]
Good question.

> WHERE rowid IN ( ... )

This is correct, and ultimately what is required in order to perform the desired query.

> SELECT rowid FROM database2 WHERE key IN (?)

You'd actually get better performance with:
SELECT rowid FROM database2 WHERE collection = ? AND key IN (?)

Because it would make use of the existing compound index on (collection, key).

However, you've made a good point that the API doesn't do a good job of making it easy to obtain the rowid's. I've addressed this in a recent commit. Let me know what you think.

From YapDatabaseSecondaryIndex.h
```objective-c
/**
 * This method assists in performing a query over a subset of rows,
 * where the subset is a known set of keys.
 * 
 * For example:
 * 
 * Say you have a bunch of tracks & playlist objects in the database.
 * And you've added a secondary index on track.duration.
 * Now you want to quickly figure out the duration of an entire playlist.
 * 
 * NSArray *keys = [self trackKeysInPlaylist:playlist];
 * NSArray *rowids = [[[transaction ext:@"idx"] rowidsForKeys:keys inCollection:@"tracks"] allValues];
 *
 * YapDatabaseQuery *query =
 *   [YapDatabaseQuery queryWithAggregateFunction:@"SUM(duration)" format:@"WHERE rowid IN (?)", rowids];
**/
- (NSDictionary<NSString*, NSNumber*> *)rowidsForKeys:(NSArray<NSString *> *)keys
                                         inCollection:(nullable NSString *)collection;
```
