### ISSUE TITLE
Fetch record changes before CloudKit extension finish restore upload queue will lead to CKErrorServerRecordChanged(CKError 14).

### ISSUE THREAD

**Issue by ainopara** [yapstudios/YapDatabase#247]
if 
```
- (void)fetchRecordChangesWithCompletionHandler:(void (^)(UIBackgroundFetchResult result, BOOL moreComing))completionHandler
```
called and got CKRecords from server when CloudKit extension not finish filling masterQueue with persisted queue data in database file, then some records in upload queue that should by removed will be uploaded to server and get the CKError code 14.

It can be resolved by suspend `fetchQueue` and `setupQueue` until CloudKit extension finish it's tasks.

**Comment by robbiehanson** [comment]
I'm not sure I'm following.

> when CloudKit extension not finish filling masterQueue

By this do you mean the following hasn't been called yet:
```objective-c
[parentConnection->parent->masterQueue restoreOldChangeSets:orderedChangeSets];
```

The reason I'm confused is because a call to [YapDatabase registerExtension] is the equivalent of a readWriteTransaction. In other words:

```objective-c
[YapDatabase asyncRegisterExtension:ext withName:@"foo" completionBlock:NULL];
[databaseConnection asyncReadWriteWithBlock:^(YapDatabaseReadWriteTransaction *transaction){

    // Guaranteed to execute AFTER extension is registered.
}];
```

The ```fetchRecordChangesWithCompletionHandler``` method uses an asyncReadWrite transaction. So it should be guaranteed to execute after the CloudKit extension is registered. And thus after the masterQueue has been restored.

It sounds like maybe you're seeing a bug that I'm missing. Can you help me ?

**Comment by robbiehanson** [comment]
I'll be happy to re-open this issue if you can provide more information.
