### ISSUE TITLE
How can I check that the object has been saved?

### ISSUE THREAD

**Issue by uranpro** [yapstudios/YapDatabase#249]
I have troubles with saving, want to check.

**Comment by xinwo** [comment]
how about call "readWithBlock" after save to check if you can load the object you just saved

**Comment by jsutwanttohelp** [comment]
Wouldn't it be better if YapDatabase told the caller whether the transaction was successful?

**Comment by robbiehanson** [comment]
As xinwo said, the correct way to check that your object was properly written to the database is to read it back. I'd also recommend ensuring that you're reading the object back from disk, and not simply from the cache. That is, each connection has an object cache. So:

```objective-c
[databaseConnection readWriteWithBlock:^(YapDatabaseReadWriteTransaction *transaction){

    [transaction setObject:user forKey:user.uuid inCollection:@"users"];
}];
// For debugging
[databaseConnection readWithBlock:(YapDatabaseReadTransaction *transaction){

    MYUser *aUser = [transaction objectForKey:user.uuid inCollection:@"users"];
    // ^ that's just going to return 'user' from the in-memory cache

    NSAssert([aUser isEqualToUser:user], @"I messed up encoding/decoding");
}];
```

To get around this problem you can:

- Just quit the app, and read the object back on next launch (quick & dirty)
- Explicitly flush the cache

```objective-c
[databaseConnection flushMemoryWithFlags:YapDatabaseConnectionFlushMemoryFlags_Caches];
[databaseConnection readWithBlock:(YapDatabaseReadTransaction *transaction){

    MYUser *aUser = [transaction objectForKey:user.uuid inCollection:@"users"];
    // ^ that's just going to return 'user' from the in-memory cache

    NSAssert([aUser isEqualToUser:user], @"I messed up encoding/decoding");
}];
```

> Wouldn't it be better if YapDatabase told the caller whether the transaction was successful?

You're confusing 2 different problems:

1. Did I properly write my encoding/decoding method for the MYUser object ?
2. Did YapDatabase/sqlite totally screw up ?

Number 1 is a typical problem that should be tested. In fact I recommend writing unit tests to automatically validate such things.

Number 2 is a completely different beast. And since @jsutwanttohelp opened a different issue concerning it (issue #251 ), I'll comment there.
