### ISSUE TITLE
Edges to files when the home directory changes

### ISSUE THREAD

**Issue by luzianscherrer** [yapstudios/YapDatabase#254]
When you run in the iOS simulator the path of NSHomeDirectory() changes each time that you relaunch the app via Xcode. According to http://stackoverflow.com/questions/25233386/xcode-6-keeps-renaming-my-apps-directory-in-ios8-simulator-after-each-run the same happens on users devices too whenever they update to a newer version of the app. How is this handled with YapDatabase edges to files? Are they stored relative to NSHomeDirectory()? For now I'm just testing with the simulator and my edges do not work after restarting the app via Xcode.

**Comment by robbiehanson** [comment]
Related to issue #117 

> How is this handled with YapDatabase edges to files?

Not well apparently. I've been meaning to switch from filePaths (NSString) to fileURLs (NSURL). It looks like this issue needs to be moved up in priority, so I'll target it for v2.8.

In the meantime, try the following as a workaround:

Apple discusses bookmark URL's here:
https://developer.apple.com/library/ios/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/AccessingFilesandDirectories/AccessingFilesandDirectories.html

Take a look at the section "Locating Files Using Bookmarks", where they discuss converting from NSURL to bookmark data (NSData).

Then apply this concept using the destinationFilePathEncryptor & destinationFilePathDecryptor. (see [YapDatabaseRelationshipOptions.h](https://github.com/yapstudios/YapDatabase/blob/master/YapDatabase/Extensions/Relationships/YapDatabaseRelationshipOptions.h))  That is, instead of using these for encryption, use them to convert from NSString -> NSURL -> bookmark NSData.

**Comment by robbiehanson** [comment]
I've completely revamped the YapDatabaseRelationship extension. It now uses NSURL's instead of strings (for storing destination file references).

To use it, check out the v2.8 branch.

If you were using destinationFilePathEncryptor & destinationFilePathDecryptor, then be sure to setup YapDatabaseRelationshipOptions.migration.

Let me know if you have any questions.

**Comment by jasonsilberman** [comment]
Hi, I seem to be having this issue too now. How can I set this up so I can keep track of the files after a relaunch and/or update to the app? I can't quite seem to figure this out.

Thanks

**Comment by luzianscherrer** [comment]
@robbiehanson thanks for the updates and the information!
@jasonsilberman just to not leave this thread unanswered: I've restorted to a manual implementation of deleting referenced files. It was not that much work and it was just way more transparent in my case.

**Comment by robbiehanson** [comment]
@jasonsilberman If you're using v2.8 or later, this should happen automatically now. As in, the NSURL will automatically follow the file if it's moved.
