### ISSUE TITLE
How do I handle relationships when using CloudKit?

### ISSUE THREAD

**Issue by jasonsilberman** [yapstudios/YapDatabase#262]
Hello, I have an app with with a data schema similar to this:
```
[Folder] 
    |---> [File] ---> binary file stored on disk,
    |---> [File] ---> binary file stored on disk,
    |---> [File] ---> binary file stored on disk
```

How can I use the CloudKit extension to sync all of these objects and relationships to iCloud? I know there are the `CKReference` and `CKAsset` classes but I am not sure how to implement them in terms of YapDatabase.

Thanks!

**Comment by robbiehanson** [comment]
Are these files related to objects in the database ?

**Comment by jasonsilberman** [comment]
Yes, so the `File` is also a database object that is has been related to a `Folder` object.

And then each `File` has an actual binary image that is stored on disk.

**Comment by robbiehanson** [comment]
Ah, gotcha.

Essentially the CloudKit extension assists you in creating a queue of CKRecords that need to be pushed to the cloud. (And then it dutifully uploads the items in the queue.) But the queue management itself is important because individual uploads may fail. (E.g. the network goes down, or the upload is rejected because of a conflict.) Or the app may be quit before all the scheduled uploads complete. So it's essential that the queue is persisted (which CloudKit does by storing it in the database) so that the queue can be picked up wherever it last left off.

There are 2 ways in which you can add items to the queue:
- "automatically" via the RecordHandlerBlock
- "manually" via ```saveRecord:databaseIdentifier:``` method

Since you already have a ```File``` object in the database, it's likely that the RecordHandlerBlock will be the easiest way for you to create a CKRecord to hand to YapDatabaseCloudKit.

Have you seen the wiki page for YapDatabaseCloudKit ?
https://github.com/yapstudios/YapDatabase/wiki/YapDatabaseCloudKit

Let me know if I can explain any particular topics in more depth. Or answer any particular questions.

**Comment by jasonsilberman** [comment]
So I have it uploading the `Folder` and `File`, what I am more wondering about is how to upload the actual images when the path is stored in like `File.imageURLPath`. Because I know CloudKit has the idea of "assets" and `CKAsset`, but how do I implement that into YapDatabaseCloudKit?

I think I am going to try and attach a `CKAsset` to the `CKRecord` in the RecordHandlerBlock. I'll let you know if I have any more questions.
