### ISSUE TITLE
Do I have to call setObject:forKey:inCollection: to update database object?

### ISSUE THREAD

**Issue by robyzhou** [yapstudios/YapDatabase#264]
Hi,

I'm on the way to migrate CoreData to YapDB, it's really a awesome framework. I have already read the wiki twice.

And I'm trying to update some properties of a object in a connection block, using transaction APIs. After I changed some properties of a object, I found the object was not updated according to the modification in the later read from a new created connection. I think maybe I MUST call setObject:forKey:inCollection: to achieve that. Then I tried, and it works.

Dear robbie, I think we'd better emphasis that at a conspicuous place. Or maybe I just missed that key point you have already referred to, please help me point it out.

Thanks a lot!
-roby

**Comment by robbiehanson** [comment]
I think we'd better emphasis that at a conspicuous place

I think you’re right. YapDatabase is fundamentally different from CoreData in several ways, and this ties in with one of those core differences. It would be useful to point this out somewhere in the wiki. Perhaps in a “Migrating from Core Data” page?

I’ve talked, in the past, about the pain points of Core Data on my blog:
http://www.deusty.com/2014/01/response-coredatanext.html

Some of this could be adapted for the wiki article.

Concerning the confusion that you initially had:

In “Issue #2” of the blog post (linked above), I discussed Apples decision to use NSManagedObject’s. And how this decision cascaded into a series of threading nightmares.

One of the biggest differences is that YapDatabase doesn’t enforce a base object class on you. If you can serialize the object, YapDatabase will happily store it for you. And herein lies the big departure from Core Data. With NSManagedObject, the Core Data stack knows all about your object. Why? Because you don’t own your object, NSManagedObjectContext owns your object. (In a sense.) It’s actually kinda weird when you think about it. You change a property on an object, and somehow NSManagedObjectContext knows all about it? Like “Big Brother” watching over your shoulder... :)

YapDatabase takes a different approach. You own your objects. YapDatabase doesn’t own them. And it doesn’t secretly monitor your objects your objects for changes. So if you make changes to an object, YapDatabase has no idea. It’s your responsibility to save those changes to the database, if that’s the intention.

Let me know if you have any questions.

-Robbie Hanson



On January 19, 2016 at 1:50:39 AM, robyzhou (notifications@github.com) wrote:

Hi,

I'm on the way to migrate CoreData to YapDB, it's really a awesome framework I have already read the wiki twice

And I'm trying to update some properties of a object in a connection block, using transaction APIs After I changed some properties of a object, I found the object was not updated according to the modification in the later read from a new created connection I think maybe I MUST call setObject:forKey:inCollection: to achieve that Then I tried, and it works

Dear robbie, I think we'd better emphasis that at a conspicuous place Or maybe I just missed that key point you have already referred to, please help me point it out

Thanks a lot!
-roby

**Comment by robyzhou** [comment]
Dear Robbie,

Thanks a lot for your reply! You make me clear on the updating issue.

I think it's needed to add a “Migrating from Core Data” page to wiki to help someone like me use YapDatabase quickly. YapDatabase is fundamentally different from CoreData in several ways, so if we point these differences out before, that would be helpful to the users.

Furthermore, I am reading the closed issues to get more info about YapDatabase. I think if you answered or discussed some topic which is import to YapDatabase users, it would be good to add these key points to the proper wiki pages in case the users miss it.

Thank you again for your help!

-roby

**Comment by robyzhou** [comment]
Hi Robbie,

One more question, if I want delete a object, is it OK to call removeObjectForKey: inCollection: only? Or I must call setObject:forKey:inCollection: with nil as the object parameter?

Thanks a lot!

-roby

**Comment by robbiehanson** [comment]
If you call setObject:forKey:inCollection: with nil as the object parameter, it will simply invoke removeObjectForKey:inCollection:

https://github.com/yapstudios/YapDatabase/blob/master/YapDatabase/YapDatabaseTransaction.m#L4354

So it's probably preferred that you directly invoke removeObjectForKey:inCollection:, as it's faster and more clearly reflects the intention of the code.

**Comment by robyzhou** [comment]
Thanks Robbie! You saved my life.
