### ISSUE TITLE
YapDatabaseViewMappings view range

### ISSUE THREAD

**Issue by pwerry** [yapstudios/YapDatabase#267]
We have the following scenario:
 - A view (filtered or otherwise) with multiple dynamic groups
 - Mappings that sort and filter those groups
 - Fixed ranges on some specific groups

What I'd like to do is apply a range (or in the simplest case, a limit) on the full set of data returned through the mappings. What this means in practice is that some groups past the range would be entirely removed, and the groups straddling the range would have their ranges constrained accordingly. 

That's the high level generic case, the real use case I'm facing at the moment is just to apply a limit to the overall size of the data returned from the mappings given the above scenario. 

Is this currently possible?

**Comment by robbiehanson** [comment]
If I understand your use case correctly, then mappings won't completely solve your problem. But the view & mappings can provide the logic that you can build upon to write the proper custom code.

The problem you're going to run into is that mappings only allow you to set ranges on a per-group basis. And, as I understand it, you additionally want to enforce a range on the total amount of data displayed in the table. (tableView, collectionView, customView, etc)

This will require some additional logic on your part. But you can use the information from the view & mappings to simplify this logic.

For example, let's say you're interested in displaying the current New York Times Bestseller list, but you want to limit the total list to only 25 items. You want to group them within the tableView according to genre, using a a pre-set arrangement of genres. The problem is that on any given day, you have no idea how many items in each genre will be on the Bestseller list. It could be 0, it could be 10. You do, however, want to restrict any one genre to a max of 5 items.

(Let me know if this example is way off base.)

To solve this particular problem, you could do something like this:

- Start by making a method that will use the view+mappings to generate the initial list. (E.g. it returns your groups & collectionKeys per group, limited to 25 items in total.)
- Use this to initially populate your tableView.
- When you receive a YapDatabaseModifiedNotification, then update your connection & mappings, and then use your custom method to generate a new (updated/different) list.
- At this point you have the previousList & newList.

You can then compare the previousList & newList in order to generate the changes/animations needed for the tableView.

Let me know if this helps, or if you have any other questions. Or if I completely misunderstood the question.
