### ISSUE TITLE
Changing sorting but not grouping for a view

### ISSUE THREAD

**Issue by sbooth** [yapstudios/YapDatabase#286]
I'm interested in changing the sorting- but not the grouping- for a view in response to user input.  I have a table displaying data from a view and the sort order is determined by the table column headers (standard Cocoa behavior, like in iTunes when a user wants to sort the tracks).  Since I know the grouping is good and doesn't need to change, I don't want to re-test thousands of objects for group membership only to change the sorting.

@robbiehanson mentioned in issue #222 that `YapDatabaseViewTransaction` `-setSorting:versionTag:` is on the wish list.  I attempted to implement this and failed, mostly because I'm not familiar enough with YapDB internals.

I also have been wondering if there is a better way to accomplish this with YapDB.  What is the preferred way to implement sorting of data from a view, for presentation in a table, based on user-specified sort criteria?

**Comment by robbiehanson** [comment]
```setSorting:versionTag:``` is still on the wish list. In fact, it's towards the very top of the list because I personally need it for something I'm currently working on. :)

I'm actually planning to start working on it as soon as I get v2.9 out the door.

> What is the preferred way to implement sorting of data from a view [?]

It's the sorting block. But, like you mentioned, when the grouping block doesn't need to be changed, then ```setGrouping:sorting:versionTag:``` is overkill. The absence of ```setSorting:versionTag:``` is sorely noticed.

**Comment by sbooth** [comment]
That's great to know, thanks! If I can help at all please let me know.
