### ISSUE TITLE
Upgrade database slow issue

### ISSUE THREAD

**Issue by strox** [yapstudios/YapDatabase#300]
hello,

I'm working on an mail app using YapDatabase. My problem is when the object is modified(add or remove the property),  the update is very slow.  

Reason:
1. the secondary Index and views will be rebuilded, so all objects will be deserialized. 
2. the database is very large. Many users has GB size database.

Because of this , we are forced to use other db solution. Is there any solution to fix this issue?

**Comment by robbiehanson** [comment]
Let's see if we can get to the bottom of this.

> My problem is when the object is modified(add or remove the property), the update is very slow.

Just to ensure I'm understanding the problem correctly, you mean modifying an object in this manner:
```objective-c
[databaseConnection asyncReadWriteWithBlock:^(YapDatabaseReadWriteTransaction *transaction){
    SomeObject *obj = [transaction objectForKey:key inCollection:collection];
    obj = [obj copy];
    obj.property = newValue;

    [transaction setObject:obj forKey:key inCollection:collection];
}];
```

> the secondary Index and views will be rebuilded, so all objects will be deserialized.

This is not correct. When you modify a single object within the database, the secondary index will only update a single row in the database. We're talking about a very minimal change. (In fact, it's similar to the change you would see in a normal sqlite database, if you changed a value in a row that was indexed.)

And YapDatabaseView works in a similar way. If the change doesn't modify the end result of the view in any way, then the view doesn't even write anything to disk. Otherwise, the view should be extremely efficient in re-sorting the object. It has several optimizations, and usually only has to deserialize 1 or 2 objects in order to re-sort it (and those objects are often cached).

Can you give me any more information. What property are you changing? Is this property part of the secondary index? Does this property affect grouping/sorting of any View. How is your database configured?

**Comment by strox** [comment]
Hi robbiehanson,


Let me make this more clear. Thanks for your explanation.


I mean the class will be modified not the object.


For example, I have a class as below

```

@interface Mail : NSObject

       @property (nonatomic, strong) NSString *subject;

@end

```


After some versions, the class is modified to this

```

@interface Mail : NSObject

       @property (nonatomic, strong) NSString *subject;

       @property (nonatomic, strong) NSString *date;

@end

```


The field "date" will be used for  grouping/sorting and is the part of
secondary index.

 When we release the new app, the version tag of secondary index will be
increased.


This is the time cost when the new version app first opened:

[image: Inline image 1]


As the picture shows, about 200 mails will cost 3.7 seconds to rebuild
secondary index. Our customers have GB size database and the cost much more
time. Sometimes the app will be killed by the system because of long
launching.


Build views is also very slow if the app already have large local data. I
know the views can be persist to database. But if we add a field to the
class, the views need be rebuild in some situation.


I think Serialize&Deserialize is the bottleneck to Yapdatabase. Yapdatabase
is suite to the app that don't have large local data.  How do you think
about my opinion?

On Tue, Mar 15, 2016 at 7:10 AM, Robbie Hanson <notifications@github.com>
wrote:

> Let's see if we can get to the bottom of this.
>
> My problem is when the object is modified(add or remove the property), the
> update is very slow.
>
> Just to ensure I'm understanding the problem correctly, you mean modifying
> an object in this manner:
>
> [databaseConnection asyncReadWriteWithBlock:^(YapDatabaseReadWriteTransaction *transaction){
>     SomeObject *obj = [transaction objectForKey:key inCollection:collection];
>     obj = [obj copy];
>     obj.property = newValue;
>
>     [transaction setObject:obj forKey:key inCollection:collection];
> }];
>
> the secondary Index and views will be rebuilded, so all objects will be
> deserialized.
>
> This is not correct. When you modify a single object within the database,
> the secondary index will only update a single row in the database. We're
> talking about a very minimal change. (In fact, it's similar to the change
> you would see in a normal sqlite database, if you changed a value in a row
> that was indexed.)
>
> And YapDatabaseView works in a similar way. If the change doesn't modify
> the end result of the view in any way, then the view doesn't even write
> anything to disk. Otherwise, the view should be extremely efficient in
> re-sorting the object. It has several optimizations, and usually only has
> to deserialize 1 or 2 objects in order to re-sort it (and those objects are
> often cached).
>
> Can you give me any more information. What property are you changing? Is
> this property part of the secondary index? Does this property affect
> grouping/sorting of any View. How is your database configured?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yapstudios/YapDatabase/issues/300#issuecomment-196558914>
> .
>



-- 
Thanks,
Harvey Zhu

**Comment by robbiehanson** [comment]
There are a few questions and concerns here. And I want to make sure I address all of them.

> Build views is also very slow if the app already have large local data.

This is a frequently asked question. And rather than answering it briefly here, I want to point you to my extended answer in the FAQ section:

https://github.com/yapstudios/YapDatabase/wiki/Frequently-Asked-Questions#registering_view

_Please read the above FAQ response before continuing, as I'm going to draw on that answer for the rest of my response._

> But if we add a field to the class, the views need be rebuild in some situation.

What you're saying here is: If I want to rebuild a view, the database has to rebuild the view.
This is really no different than if you were using SQLite directly, and you said: If I want to rebuild an index, the database has to rebuild the index.

I'm not trying to belittle your concerns. I'm simply trying to draw a parallel between the FAQ (registering a view for the first time), and this concern (re-registering a view). In essence, they are the same thing.

> Sometimes the app will be killed by the system because of long launching.

If this is the case, then the primary problem is that you're registering/re-registering your view synchronously. I.e. you're performing a lot of synchronous disk IO on the main thread, and blocking your app. This is strongly discouraged, in the same way that performing synchronous network IO on the main thread is strongly discouraged.

The FAQ mentions this:

> keep in mind that registering a view (or registering any extension for that matter) is the equivalent of performing a read-write transaction. And you're strongly encouraged to register your extensions asynchronously. Thus the overhead of setting up your views is no different than an asyncReadWrite transaction. That is, it's relegated to a background thread that won't block your UI. In fact, there's even an FAQ question regarding dealing with [asyncRegisterExtension](https://github.com/yapstudios/YapDatabase/wiki/Frequently-Asked-Questions#asyncRegisterExtension).

Let me know if you have any other questions.
