### ISSUE TITLE
Why is YapDatabaseEnforcePermittedTransactions only enabled for DEBUG build?

### ISSUE THREAD

**Issue by king7532** [yapstudios/YapDatabase#309]
I'm using YapDatabase in a Swift app and when I did a RELEASE build I was surprised to learn that `YapDatabaseEnforcePermittedTransactions` (YapDatabaseConnection.h) is only enabled for DEBUG builds?  I'm curious if there is a reason behind that?  Do you recommend for RELEASE builds we do not use `permittedTransactions` on `YapDatabaseConnection`s?

**Comment by robbiehanson** [comment]
Good question. My thinking was that, since this does add a small bit of overhead, and the overhead is primarily intended to assist developers during the development cycle, that a reasonable default would be to only enable the setting for DEBUG builds.

Note, however, that it's not enforced this way:
```objective-c
#ifndef YapDatabaseEnforcePermittedTransactions
  #if DEBUG
    #define YapDatabaseEnforcePermittedTransactions 1
  #else
    #define YapDatabaseEnforcePermittedTransactions 0
  #endif
#endif
```

This means that you can define ```YapDatabaseEnforcePermittedTransactions``` within your build settings, and that will override the code in YapDatabaseConnection.h.

> Do you recommend for RELEASE builds we do not use permittedTransactions on YapDatabaseConnections?

When you disobey the permittedTransactions, the code with throw an exception. While this is the proper thing to do during the development cycle, is this what we'd want to occur in a shipping app? What are the real-life consequences of disobeying the permittedTransactions? Generally speaking, not very much. For example, you might be enforcing read-only transactions on a databaseConnection designed to be used for reading on the user-interface thread. This is certainly a good idea. But if you accidentally perform a read-write transaction the consequences are... maybe a slight hiccup on the main thread. Certainly not desirable, but probably not something we'd want to crash in a shipping app.

But, obviously, RELEASE is not strictly for shipping an app. I will often test in RELEASE mode, especially when analyzing performance issues. So my recommendation would likely be to integrate ```YapDatabaseEnforcePermittedTransactions``` into your build settings in a manner that works best for you. (And I was hoping the default configuration would be appropriate for the majority.)

Let me know if you have any other questions.

**Comment by king7532** [comment]
@robbiehanson thank you for the thorough and quick response.  For my app, I decided to remove the `permittedTransactions` on my instance of `YapDatabaseConnection`.  However, your response to just enable the `YapDatabaseEnforcePermittedTransactions` preprocessor macro definition during a build is complicated if you're using YapDatabase as a CocoaPod dependency.  I spent many hours googling and trying various build configurations to no avail.  I'll leave this an exercise for the next developer.

**Comment by uthiel** [comment]
The following code:

`#if YapDatabaseEnforcePermittedTransactions
		self.uiDatabaseConnection.permittedTransactions = YDB_SyncReadTransaction | YDB_MainThreadOnly;
#endif`

results in 
`-[YapDatabaseConnection setPermittedTransactions:]: unrecognized selector sent to instance 0x7f85ca615000`

How can I supply a DEBUG and release version of YapDB to my project? I'm using Carthage. Thanks in advance for any hints.

**Comment by robbiehanson** [comment]
As mentioned above, you can control whether or not 'YapDatabaseEnforcePermittedTransactions' is set to ON or OFF.

So, the easy fix, would simply be to turn it ON in your Carthage build of the framework. And then you cold optionally just not use it (not call setPermittedTransactions) in your RELEASE build.

Another possible solution (and I'm not even sure this would work), would be to build 2 versions of the YapDatabase framework. One in DEBUG and the other in RELEASE. The unknown here is how to link each properly within Xcode. I don't think there's a simple way to accomplish this. Which means you'd probably have to write a little script that runs as a step in the build process, and changes a soft-link on the filesystem to point at the correct framework for the current build. (I've never tried this, but it seems like it could work.)

That being said... Carthage isn't really a flexible build system. It's really simple, and you don't really have to learn much in order to use it. I get that. And it's great for that purpose. But I can't tell you how many times I've heard something along the lines of: "So I've been using Carthage, but now I want/need to do this additional thing for my build..."

**Comment by robbiehanson** [comment]
@king7532 (and those who have the same question)

One can inject additional build settings into a CocoaPod project via the 'post_install' hook. Which is just some code you can add to your Podfile.

There's some sample code in this [StackOverflow question](https://stackoverflow.com/questions/27133993/why-isnt-my-cocoapods-post-install-hook-updating-my-preprocessor-macros) that does something very similar.
