### ISSUE TITLE
Publicclouddatabase

### ISSUE THREAD

**Issue by johnisburt** [yapstudios/YapDatabase#317]
Hi there, when i enable the databaseidentification block and change to identifier to public (publicloufddatabase) i get all kinds of errors because half the things you can do with privateclouddatabase are not applicable to  public. Zones are not aloud or implemented, so all subscriptions and zones fail. I believe some of the functions are not applicable either.

I am only raising this issue as your instructions go into detail about databaseidentification blocks etc.

Can it be done?

**Comment by robbiehanson** [comment]
> Can it be done?

It depends on what you mean by "it" :smiley:

There are 2 distinct code bases here, and it's important that we keep them separate:
- YapDatabaseCloudKit (the framework itself)
- CloudKitTodo (a specific example built on top of the framework)

Does YapDatabaseCloudKit support the publicCloudDatabase ? YES
Does CloudKitTodo support the publicCloudDatabase ? NO

CloudKitTodo is just a sample app. One that is designed for a specific purpose: syncing a personal Todo list across a user's devices. The very nature of this task is designed for the privateCloudDatabase. But this shouldn't be a reflection on the YapDatabaseCloudKit framework as a whole. It's just one possible example.

As you know, Apple has different rules for the privateCloudDatabase vs the publicCloudDatabase:

- Zones cannot be created in a public database.
- You can't create a subscription for the default zone

When these rules are looked at from the perspective of the CloudKitTodo app, they look rather restrictive. But Apple created these rules for a reason. The publicCloudDatabase is meant to be a very different animal from the privateCloudDatabase. The public version is meant to be ... public. And is meant to scale to hundreds of thousands of users. Can you imagine the CloudKitTodo app being used to create a "shared todo list" between 1 million users? Besides being a ridiculous app nobody would want to use, the scalability of such a design would suffer horribly.

I believe the general idea behind the publicCloudDatabase is something like this:
- it's designed for a LOT of users to be adding items concurrently
- it's designed for records to be query-able based on very specific criteria (not everything)

For example: An app where people create events, and tag them with a city & time. Other users might then create subscriptions, not for every possible event, but one's in their own city. Maybe filtered by event type.

That being said, one can still get creative with the publicCloudDatabase. For example, what if you wanted to extend the CloudKitTodo app to support:
1. multiple todo lists
2. sharing a specific list between multiple users

In order to implement step 1, we do the following:

First we add a listUUID field to the "todo" item. So now every todo item in a particular list with have the same "listUUID" field.

Next we create a new record type called "list". It really only needs 2 fields: uuid & name.

So when the user creates a new list, we simply create a new "list" item in the database. And renaming a list? No problem, just modify the "list" item.name field, and it will automatically sync across devices.

Now for step 2:

When the user creates a shared list, we want to store it in the publicCloudDatabase. But how to do it?

Let's say Alice wants to share/collaborate on a list with Bob. So she creates a new shared list, and sends Bob an "invite". (I'll leave the details of the invite to your imagination.) Now Alice & Bob both have a listUUID that represents the shared list. And all todo items that are added to the shared list will be saved to the publicCloudDatabase. So Alice & Bob create a subscription to the defaultZone of the publicCloudDatabase that uses a query like:

record="todo" & todo.listUUID="ourSharedListUUID"

So if Alice adds a todo item to the shared list, it will be saved in the publicCloudDatabase, but only Bob and Alice will get a notification about it.

Hope this helps. Let me know if you have any other questions.

**Comment by johnisburt** [comment]
Thank you for your reply, yes i completely understand now.
Cheers
John

**Comment by uthiel** [comment]
Unfortunately, CloudKitManager also has to changed, because a `CKFetchRecordChangesOperation` does not support syncing the default zone, and consequently not the public db, resulting in a "AppDefaultZone does not support getChangesSince call" error. What would be the appropriate code to fetch changes from the public db?
