### ISSUE TITLE
Reachability Not Support for IPv6

### ISSUE THREAD

**Issue by XiongCaixing** [yapstudios/YapDatabase#331]
"tonymillion/Reachability" Not Support for IPv6

**Comment by JamieWhite** [comment]
Why is this still a dependency when we have this https://github.com/yapstudios/YapDatabase/blob/aaf17f1c27d3bd1770cd52e42c03c6a31f1c39fa/YapDatabase/Extensions/ActionManager/Utilities/YapReachability.m

**Comment by robbiehanson** [comment]
It's only because that change was made after the last version release. I'm going to go ahead and tag v2.9.3, and release it now.

**Comment by JamieWhite** [comment]
Hah. I should've checked the commit date!

**Comment by robbiehanson** [comment]
I'm trying to push the latest Podspec, but CocoaPods is giving me problems. Again...

From what I can tell, this time it won't validate because CocoaPods [broke compiling C files](https://github.com/CocoaPods/CocoaPods/pull/5844). This translates into:
- [SQLCipher](https://github.com/sqlcipher/sqlcipher)'s podspec doesn't work (trying to compile sqlite.c)
- And thus the YapDatabase.podspec won't lint (depends on SQLCipher)
- Which means I can't push it via `pod trunk push` (and they don't supply a `--force` option)

This is with CocoaPods 1.1.0.rc.2

I ran into problems with CocoaPods last time, when I went to push v2.9.2. It ended up taking me all day to sort things out. And I just don't enough time today to continue fighting CocoaPods.

Note: @chrisballinger appears to have a [workaround](https://github.com/ChatSecure/ChatSecure-iOS/blob/cocoapods_1.0.1/Podfile) that works for normal Podfile's. However, this won't work for a Podspec, because dependencies (within a Podspec) only allow for version requirements. So I'm a bit stuck at the moment.

**Comment by chrisballinger** [comment]
I bumped the CocoaPods issue again.. I'll see if I can raise some more noise.

In our project we maintain a [custom version of SQLCipher.podspec](https://github.com/ChatSecure/ChatSecure-iOS/blob/develop/Podspecs/SQLCipher.podspec.json) that renames the .c to .m to work around this bug, but it's not something that will fix the podspec linter issues for pushing YapDatabase.

An absolutely insane solution would be to use a Gemfile to use the pull request branch just to push the podspec, but it would remain broken for other people trying to use SQLCipher unless they also override in their Podfile with my workaround podspec. If you want to investigate that option I can try to provide instructions.

**Comment by JamieWhite** [comment]
I've been a Carthage user for the last year. I love not having to deal with this crap anymore.

**Comment by chrisballinger** [comment]
@robbiehanson After bumping the issue again they finally merged the PR that fixes this and just released 1.1.0.rc.3 which should include the change. :)
