### ISSUE TITLE
Integration with SQLCipher for Encryption

### ISSUE THREAD

**Issue by brendand** [yapstudios/YapDatabase#4]
Hi,

Would it be possible to use SQLCipher (http://www.sqlcipher.net) instead of the built-in SQLite engine? I don't see why not, but I'm just asking for clarification.

**Comment by fmessina** [comment]
Hi,
I'm having some troubles using YapDatabase with SQLCipher.

I'm not using CocoaPods so I did the setup manually (setting all the required compiler flags too), since I was already using SQLCipher for another sqlite database.

The creation of the database looks exactly like the one described in the "encryption" page of the wiki.
I'm passing a ```YapDatabaseOptions``` object with the passphrase block and it creates the database correctly.

The problem is that after creating the ```YapDatabase``` instance - that is hold by a singleton, whenever I try to create a new connection to the database I get always the same error:
```26 file is encrypted or is not a database```

I've tried the simple "hello world" for yap database and this is what I have with verbose logging.
The first line of the log is part of the ```YapDatabaseOptions```  passphrase block, confirming that apparently I'm reading the passphrase correctly.

> ACCESSING DATABASE KEY = testDatabaseKey
> YapDatabase: Created new connection(0x14de00f0) for <YapDatabase 0x14e93a70: databaseName=Services2.sqlite, connectionCount=1>
> YapDatabaseConnection: YapDatabaseConnection(0x14de00f0) starting read-write transaction.
> YapDatabaseConnection: Error creating 'getRowidForKeyStatement': 26 file is encrypted or is not a database
> YapDatabaseConnection: YapDatabaseConnection(0x14de00f0) completing read-write transaction.
> YapDatabaseConnection: Error creating 'getDataForKeyStatement': 26 file is encrypted or is not a database
> (null) World
> YapDatabaseConnection: YapDatabaseConnection(0x14de00f0) completing read-only transaction.

I have the same error if for example I try to register a ```YapDatabaseView``` extension.

What is interesting is that if I try the "hello world" code immediately after the database creation, it works fine:
> ACCESSING DATABASE KEY = testDatabaseKey
> YapDatabase: Created new connection(0x17ee6eb0) for <YapDatabase 0x17ee5580: databaseName=Services2.sqlite, connectionCount=1>
> YapDatabaseConnection: YapDatabaseConnection(0x17ee6eb0) starting read-write transaction.
> YapDatabase: Adding pending changeset 1 for database: <YapDatabase: 0x17ee5580>
> YapDatabase: Dropping processed changeset 1 for database: <YapDatabase: 0x17ee5580>
> YapDatabaseConnection: YapDatabaseConnection(0x17ee6eb0) completing read-write transaction.
> YapDatabase: Checkpointing up to snapshot 1
> Hello World

Do you have an idea of what possibly I'm doing wrong?
Thanks a lot..

**Comment by chrisballinger** [comment]
@fmessina Double check to see if your preprocessor definitions are correct (e.g. SQLITE_HAS_CODEC) and put breakpoints on all calls to sqlite3_key to verify it's being called.

**Comment by fmessina** [comment]
@chrisballinger Hi,
I've debugged it with breakpoints in different cases and yes, it's called every time I create a new connection.
More in particular, it's called every time during the connection creation in the method
 ```- (id)initWithDatabase:(YapDatabase *)inDatabase``` 
the code enters this if statement:
https://github.com/yapstudios/YapDatabase/blob/master/YapDatabase/YapDatabaseConnection.m#L201

but however I get the same error.
Never seen this before while using YapDatabase with SQLCipher?

**Comment by chrisballinger** [comment]
@fmessina Are you 100% sure this is being called? https://github.com/yapstudios/YapDatabase/blob/master/YapDatabase/YapDatabaseConnection.m#L270

**Comment by fmessina** [comment]
@chrisballinger unfortunately I cannot check right now to give you 100% sureness but I will update you as soon as possible.
Thanks

**Comment by fmessina** [comment]
@chrisballinger I've checked again and the method ```[database configureEncryptionForDatabase:db];```
is being called, at least the very first time.
The result of ```sqlite3_key(sqlite, key, (int)keyLength)``` is zero, but I still get the same error immediately after:
>  YapDatabaseConnection: YapDatabaseConnection(0x145a5680) starting read-write transaction.
>  YapDatabaseConnection: Error creating 'getRowidForKeyStatement': 26 file is encrypted or is not a database
> YapDatabaseConnection: YapDatabaseConnection(0x145a5680) completing read-write transaction.

After that what I noticed is that whenever I create a new connection, the ```sqlite3_key``` is never called again, I assume due to the ```connectionPoolDequeue```
> YapDatabase: Dequeuing connection from pool: 0x14aa5c00
