### ISSUE TITLE
The WAL file getting spoiled when switching back to app from an app extension

### ISSUE THREAD

**Issue by 1nput0utput** [yapstudios/YapDatabase#420]
It would seem that 3.0.1 fixed a lot of issues related to checkpoint #197. I am unfortunately still have an issue where the WAL file keeps growing beyond the size limit, and this only happens when I switch back to the app from an app extension. 

I suspect that my read connection is not closing properly because if I flush memory with flags`YapDatabaseConnectionFlushMemoryFlags.caches` &`YapDatabaseConnectionFlushMemoryFlags.statements` in YapDatabaseModifiedExternally while also making sure that after each read I endLongLivedReadTransaction so that the next readWrite operation can clear the WAL file.

**Comment by robbiehanson** [comment]
You should treat `YapDatabaseModifiedExternally` similarly to how you treat YapDatabaseModified. In particular, it's critically important that you properly invoke `endLongLivedReadTransaction` when receiving `YapDatabaseModifiedExternally` just as you would for `YapDatabaseModified`.

A longLivedReadTransaction will prevent the WAL from being properly checkpointed & truncated, regardless of what process that transaction resides in. I.E. a longLivedReadTransaction in the main app will prevent the WAL from getting properly truncated over the in app extension. (Because they are all sharing the same SQLite file.)

More information about this can be found [here](https://github.com/yapstudios/YapDatabase/wiki/LongLivedReadTransactions#important-warning).

Let me know if this doesn't solve the issue you're seeing.
