### ISSUE TITLE
CloudCore Object Updates

### ISSUE THREAD

**Issue by dezinezync** [yapstudios/YapDatabase#429]
Hi Robbie, thank you for the update in #427. That did allow me to register the extension properly. 

Once registered, I was able to debug things further and noticed the following in `YapDatabaseCloudCoreTransaction`:

```objc
- (void)didUpdateObject:(id)object
       forCollectionKey:(YapCollectionKey *)collectionKey
           withMetadata:(id)metadata
                  rowid:(int64_t)rowid
{
	// Nothing to do here
}
```

Is the implementation for the above method pending? Similar implementation exists for when deleting objects from the database. I'd imagine the following scenario would apply for several applications using a remote API:
- Insert new object: Call the associated `PUT:` URI
- Update existing object: Call the `POST:` URI
- Delete existing object: Call the `DELETE:` URI
or similar depending on the API's structure. 

Given the above, I believe it would make sense to have those implementations in there so when `- [YapDatabaseCloudCore commitAddedGraphs:insertedOperations:modifiedOperations:]` is called, it would have the right counts therefore leading to a graph being created in the registered pipeline? 

This would also tie in very well for the `enableAttachDetachSupport` option when creating an instance of `YapDatabaseCloudCore`.

**Comment by dezinezync** [comment]
@robbiehanson Hi Robbie, your latest work on this extension as well as the updated wiki documentation has been great. I have the above working as expected using the Pipelines & Operations model and I've found myself really liking this model. 

I'm closing this issue as my original concern/issue is no longer valid. Thank you for all your hard work.

**Comment by robbiehanson** [comment]
I'm glad you've found it useful !

In response to the original question (you probably already figured this out, so I'm answering this for others who may have a similar question, and come across this thread):

YDBCloudCore is primarily concerned with tracking YDBCloudOperation objects. But it doesn't make any assumptions, nor have any idea as to how your objects map to various operations.

So if a new object is added to the database, does this correspond to a YDBCloudOperation? CloudCore doesn't know. And it's up to you to create the operation and add it to a pipeline.

Similarly, if an object is modified, does this correspond to an operation? CloudCore doesn't know. And it won't know about deleted objects either.

This makes sense conceptually, but it also doesn't help you when you're just trying to get all the pieces connected in your app. So here are a few suggestions.

If there's only a few places in your app where synced objects can be added, modified or deleted, then the answer is easy. Go modify those code paths so that the code creates and enqueues the needed operations.

But what if that's not the case? What if there's lots of places throughout your app where a synced object might be modified? In this case, you may want to take a look at YapDatabaseHooks. This allows you to setup custom code that runs in response to certain database operations, such as an item being added to the database, or being modified, deleted, etc.
