### ISSUE TITLE
support encryption with Carthage

### ISSUE THREAD

**Issue by elmyn** [yapstudios/YapDatabase#430]
When integrating with Carthage, yap db doesnt have encryption option

**Comment by robbiehanson** [comment]
This is the problem with Carthage — it support zero configuration.

If I changed the Carthage build to support encryption, then the project would get a new issue next week: "support no encryption with Carthage"

And this isn't the first time somebody has asked for something like this. I've had similar requests in the past where people said they were only using extensions X & Y, and they wanted to remove all the others in order to reduce the size of the framework. Except they were using Carthage, and so it was impossible to do.

As far as I understand it, you have 3 options:

1. Switch to CocoaPods
2. Fork the project, and change the Xcode setup (in your fork) to enable encryption.
    - Of course, this complicates keeping up with the project. As future changes may cause conflicts (as is easy to do with those goofy Xcode files).
3. Do something manual like perform:
    - carthage bootstrap
    - manual modification of Xcode project
    - carthage build
