### ISSUE TITLE
Too many warnings in Xcode 9

### ISSUE THREAD

**Issue by alexlee002** [yapstudios/YapDatabase#444]
```ObjC
if (wal_file == NULL)
{
	wal_file = yap_vfs_last_opened_wal(database->yap_vfs_shim);
	if (wal_file) {
		wal_file->yap_database_connection = (__bridge void *)self;
	}
}
```

Xcode warnings that the ivar `wal_file` should be replaced with `self->wal_file`: 

```
  Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
```

**Comment by robbiehanson** [comment]
> "Too many warnings"

Are you saying that this is the only place where there's a warning ? Or are you saying there are hundreds of warnings like this throughout the project ?

**Comment by chrisballinger** [comment]
@robbiehanson The implicit block retain self is a new warning enabled by default in Xcode 9.3

**Comment by robbiehanson** [comment]
Just turned on the compiler option. I see the warnings now. Wow... that is... annoying.

OK, so the warnings within dispatch_sync() should obviously be ignored/disabled.

And many of the warnings within dispatch_async should also be ignored because the architecture is purposely retaining the object during that time. For example, a YapDatabaseConnection should not be deallocated in the middle of an async transaction. (Therefore it purposely retains itself.)

Now, we could theoretically put this at the top & bottom of source files:

```objective-c
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wimplicit-retain-self"

// <SomeFile.m goes here>

#pragma clang diagnostic pop
```

However, I fear that's bad form ?
If this is the consensus, does that mean our only option to add this to all the blocks that are complaining ?

```objective-c
dispatch_sync(queue, ^{
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wimplicit-retain-self"

    // <code>

#pragma clang diagnostic pop
});
```

**Comment by ksuther** [comment]
You can also switch to explicitly referencing self, as the warning suggests. Unfortunately that's a pretty time consuming process.

There is a tiny side benefit in that it may catch unexpected bugs, but it is a lot of work. We found some lurking ones a couple of years ago when we started turning this on for some projects.

**Comment by mickeyl** [comment]
I agree with @ksuther that the proper way is to use `self->`. It improves code quality as it clearly states the assumptions as well. I don't think we should use the `#pragma` workaround as this can hide issues.

**Comment by Superoryco** [comment]
Any chance to update Pods in order to fix this issue?

**Comment by robbiehanson** [comment]
@Superoryco Yup, thanks for reminding me.

v3.1 is now pushed to CocoaPods. The release notes can be found in the [changelog](https://github.com/yapstudios/YapDatabase/wiki/Changelog).
