### ISSUE TITLE
Forced way to disconnect from database

### ISSUE THREAD

**Issue by mickeyl** [yapstudios/YapDatabase#454]
I can't seem to find a way to properly shutdown all connections from the database.

Due to the way iOS works, e.g. when using a `UISplitViewController`, some controllers are cached, and thus the connections they grab. I have a method in my app which downloads a fresh copy of the database, but I often get database corruption, since YapDatabase is still having the database open.

Can we get a way to force closing the database?

**Comment by robbiehanson** [comment]
Good question. I walked through this with someone in the past. Here's what we did:

As you know, the YapDatabase instance cannot be deallocated when there are open connections. And since you've got some UI views still open (using connections), you're going to need a mechanism to "flush" the connections. So, what we did, was create a custom Notification for the views to listen for. When they receive the notification, they drop their databaseConnection instance...

There is already a `YapDatabaseClosedNotification` that will be broadcast when the database is finally closed.
