### ISSUE TITLE
Pagination in YapDB Views

### ISSUE THREAD

**Issue by victorbarskov** [yapstudios/YapDatabase#481]
Hey! I have made the view and made the mappings for that view (the view is messages for a group of receivers), so that was good. I can do anything I can with my YapDatabaseViewMappings *mappings, but my problem is the following: I have 2K messages objects in db for a receiver and I need to show it to user properly in UITableView, to get all 2K messages and show it immediately in TableView is not a good idea, and as I see you have these YapDatabaseViewRangeOptions. RangeOptions are good but this is not good for pagination. So my question is how can I get limited number of messages for a mapping, paginate(add some more messages on top of the table) it while user scrolls the table and also handle the notification updates on changes in db(for example when I write new message I got from server)? Is there any workaround for mappings or should I make it with direct SQL queries and then observe somehow db changes?

**Comment by robbiehanson** [comment]
The wiki has a nice section on "flexible ranges", which sounds like what you're looking for in general:
https://github.com/yapstudios/YapDatabase/wiki/Views#flexible_ranges

For the pagination question:

There's a few things you need to do in terms of mappings/database, but the majority of work will be in your UI code. I've done this before several times, and here's how I generally coded it.

```
- (void)paginateUpAndIncreaseLength:(NSUInteger)count
{
    YapDatabaseViewRangeOptions *rangeOptions = [mappings rangeOptionsForGroup:conversationId];
    rangeOptions = [rangeOptions copyWithNewLength:(rangeOptions.length + count)];
	
    [mappings setRangeOptions:rangeOptions forGroup:conversationId];

    // A bunch of UI calculations ...

    [tableView reloadData];
    tableView.contentOffset = contentOffset; // <- result of your UI calculations
    [tableView flashScrollIndicators];
}

- (void)paginateUpAndIncreaseOffset:(NSUInteger)count
{
    YapDatabaseViewRangeOptions *rangeOptions = [mappings rangeOptionsForGroup:conversationId];
    rangeOptions = [rangeOptions copyWithNewOffset:(rangeOptions.offset + count)];

    [mappings setRangeOptions:rangeOptions forGroup:conversationId];

    // A bunch of UI calculations ...

    [tableView reloadData];
    tableView.contentOffset = contentOffset; // <- result of your UI calculations
    [tableView flashScrollIndicators];
}

- (void)paginateDownAndDecreaseOffset:(NSUInteger)count
{
    YapDatabaseViewRangeOptions *rangeOptions = [mappings rangeOptionsForGroup:conversationId];
    rangeOptions = [rangeOptions copyWithNewOffset:(rangeOptions.offset - count)];

    [mappings setRangeOptions:rangeOptions forGroup:conversationId];

    // A bunch of UI calculations ...

    [tableView reloadData];
    tableView.contentOffset = contentOffset; // <- result of your UI calculations
    [tableView flashScrollIndicators];
}
```

You can achieve "infinity scroll" using a technique like this:

- start by displaying only the most recent X messages (using a "flexible range" in your mappings)
- when the user scrolls to the top, automatically load Y more messages
- continue to do so as the user continues to scroll to the top, until they hit some max limit Z (max number of messages to display in tableView/collectionView)
- once Z is reached, if user continues scrolling to the top, then instead of loading more messages, you'll simply change the offset
- if user scrolls to the bottom, and the offset is > 0, then play the same game (of moving the offset), but in reverse (until you get the last message)

The hard part is ensuring the tableView doesn't "jump" from the user's perspective.

Before you call `[tableView reloadData]`, the height of your tableView is `H1` and the contentOffset is `O1`. But then you add a bunch of rows, and now you're at `H2`, but still `O1`.  Your job is to calculate what the new contentOffset should be (`O2`), so that the user's scroll position appears to remain fixed.

**Comment by victorbarskov** [comment]
Hey @robbiehanson! Thank you a lot! Honestly said you saved my day!
