### ISSUE TITLE
Xcode tabs/spaces/indentation settings for this project

### ISSUE THREAD

**Issue by gcox** [yapstudios/YapDatabase#484]
@robbiehanson I'm trying to submit a pull request, trying to match the tabs/spaces settings currently used by the project. Sadly, the configuration escapes me. Most everything is indented with tabs, but then [lines like this](https://github.com/yapstudios/YapDatabase/blob/master/YapDatabase/Extensions/AutoView/YapDatabaseAutoViewTransaction.m?ts=2#L911) indented with tabs **and aligned with spaces**. As far as I know, that isn't even possible in Xcode 10. Would you mind sharing how you're getting this tab/space/alignment?

**Comment by robbiehanson** [comment]
No problem. I can understand how this would be confusing.

As you already noticed, I have a peculiar way of formatting my code compared to most programmers. The short answer is that **you can submit a pull request using whatever formatting you want**. The spacing won't bother me - just so long as the code is correct I'll be more than happy to merge it.

And now for the long answer: my philosophy on indentation within open source projects:

For an open source project to be successful, there are 3 critical components:

- documentation
- code readability
- community

The question of tabs/spaces/indentation falls into the "code readability" category. Some people get religious about this stuff (as you no doubt already know), but I take a pragmatic approach. Different people have different preferences when it comes to indenting code. That is, for a single level of indentation, people have all kinds of different personal preferences:

- 2 spaces per indentation level
- 3 spaces per indentation level
- 4 spaces per indentation level
- other ?

*(Me personally, I'm a 3 spaces kind of guy. For me, 2 spaces is too little, and 4 spaces is too much - 3 spaces is just right.)*

What we know is that if a person prefers X spaces per indentation level, and they open the code and find it to be indented instead using Y spaces per indentation level, then they will be ever so slightly annoyed. And a little less likely to dive into the code, solve their problem, or submit a patch request. And that's bad.

So the question to answer is simply this:

Format the following code block so that is remains properly spaced regardless of the reader's indentation level. That is, if I set my editor to be 3 spaces per tab, the code should be properly formatted, and should be displayed using 3 spaces per indentation level. And if I change my editor to be 5 spaces per tab, the exact same piece of code must be rendered using 5 spaces per indentation level, and must properly line everything up exactly as we intended it to be:

```objective-c
- (void)someMethod
{
    if (foobar)
    {
        // The ':' must line up properly,
        // regardless of preferred indentation preferences.
        [self doSomething: @"param"
                  withFoo: @"something else"
                      bar: 42];
    }
}
```

If you attempt to indent this using spaces, you'll fail. And if you change Xcode to indent using tabs, then **Xcode will screw it up**, and you'll also fail. The solution that should be obvious to editor developers has somehow escaped them:

**It's not about tabs or spaces. It's about indentation levels.**

The `doSomething:::` method call is at indentation level 2. Thus, it should be indented using 2 tabs  - everywhere. All other alignment concerns after 2 tabs should use spaces. Like this:

```
- (void)someMethod
{
<tab>if (foobar)
<tab>{
<tab><tab>// The ':' must line up properly,
<tab><tab>// regardless of preferred indentation preferences.
<tab><tab>[self doSomething: @"param"
<tab><tab>< spaces >withFoo: @"something else"
<tab><tab>< spaces     >bar: 42];
<tab>}
}
```

You'll notice this is the ONLY solution that will render the code properly, regardless of a reader's preferred indentation settings. And this is how I attempt to format all of my open source code.

Is it extra work? Yup. Do almost all editors screw it up? Totally.

Like I said earlier, you can submit a pull request using whatever formatting you want. My real hope is that someday editor developers will offer this style of indentation as an option. And then instead of saying "tabs" or "spaces", I can simply say "indentation based".

**Comment by gcox** [comment]
@robbiehanson I'm down with your formatting, I just couldn't figure out how to make it automatic. I never imagined you were doing this *manually*🤯 Thanks for the detailed explanation!
