### ISSUE TITLE
Example needed for simple retrievals of objects

### ISSUE THREAD

**Issue by Miggets7** [yapstudios/YapDatabase#493]
Hi all,

YapDatabase seems to bee very powerful and flexible, but hard for simple tasks(or I don't get it)

I've got the following models:
```
Calendar -> ObjectId
Appointment -> ObjectId, CalendarId
```

I would simply would like to get all Calendars, without filtering. I'm doing this like this:
```
__block NSMutableArray *collection = [NSMutableArray array];

    [connection readWithBlock:^(YapDatabaseReadTransaction *transaction) {
        NSArray<NSString*> *keys = [transaction allKeysInCollection:collectionName];
        for(NSString *key in keys) {
            [collection addObject:[transaction objectForKey:key inCollection:collectionName]];
        }
    }];

    return collection;
```
Seems ok, but maybe something like allObjectsInCollection would be better?

And now I simply would like to get all appointments of a certain calendar. With my current knowledge I would do it like this:
```
__block NSMutableArray *collection = [NSMutableArray array];

    [connection readWithBlock:^(YapDatabaseReadTransaction *transaction) {
        NSArray<NSString*> *keys = [transaction allKeysInCollection:collectionName];
        for(NSString *key in keys) {
            id appointment = [transaction objectForKey:key inCollection:collectionName];
            if(appointment.calendarId eq calendarId) {
                [collection addObject:[transaction objectForKey:key inCollection:collectionName]];
            }
        }
    }];

    return collection;
```

I read a lot about Views and Groupings, but that seems all overkill for what I want to achieve. Or is this library not meant for the trivial tasks I want?

Thank you in advance!

**Comment by uthiel** [comment]
I don't know why there is no `-allObjectsInCollection:`, probably because there is no need to. Databases are used to store thousands of objects in them, there is normally no need to fetch all of them at once. If you want to display the contents, you'd use views and groupings which handle partial fetches for you.

I'd use the Relationships Extension to create and fetch Appointments from Calenders.

**Comment by Miggets7** [comment]
@uthiel you're right about databases storing lot's of objects. That still doesn't mean that's always the case or such a functionality should not be provided.

And still I can't to read from the wiki how you can do it simple. It's starts about the different types of relations and then goes on about edges, instead of just showing a simple example. That is what I'm missing from the wiki, tl;dr; instructions.

I guess this lib is just overkill for what I need.

**Comment by robbiehanson** [comment]
@Miggets7 I think you're looking for `-[YapDatabaseTransaction enumerateKeysAndObjectsInCollection:usingBlock:]`

```objective-c
[connection readWithBlock:^(YapDatabaseReadTransaction *transaction) {
    [transaction enumerateKeysAndObjectsInCollection:collectionName
                                usingBlock:^(NSString *key, id object, BOOL *stop)
   {
      // do something with object here...
   }];
}];
```

There is no `-allObjectsInCollection:` method because that functionality is discouraged.

> you're right about databases storing lot's of objects. That still doesn't mean that's always the case or such a functionality should not be provided.

As a library developer, one has to choose which features to include, and which features to skip. Generally, if a particular feature is considered a "loaded gun pointing at your foot", it gets skipped. And that's exactly what this feature is.

> I read a lot about Views and Groupings, but that seems all overkill for what I want to achieve. Or is this library not meant for the trivial tasks I want?

I'll be honest with you: early in my programming career, I refused to learn git. It just seemed like overkill for what I wanted to do. (_This was before GitHub, when using git meant using it on the command line._) I just wanted to backup my code at various points so I wouldn't lose all my work if my computer crapped out.

But eventually I was forced to learn git. One too many times I came to the painful realization as to why these tools exist, and what problems they solve.

The truth is that most programming tools are like this. Any tool that's been battle-tested by the programming community long enough has evolved to solve a wide range of problems. And as the tool becomes more useful, the learning curve often gets steeper.

YapDatabase is no exception. It started life as a simple key/value store. "Why are databases so complicated?!?!" I wondered. I just wanted a dead-simple way to store something to disk. And then, as it gained traction, it began to evolve. Today it can solve a wide range of problems in an efficient manner.

The heart of YapDatabase is still a simple collection/key/value store. I wanted additional functionality to be separate from this core, which is why YapDB has extensions. And some of these extensions have grown significantly over time. [Views](https://github.com/yapstudios/YapDatabase/wiki/Views) are the prime example of this. They've been so useful for powering tableViews & collectionViews that the functionality has expanded to support many different use cases.

I apologize if the documentation could be better. If you're still considering YapDatabase, you may find this alternative introduction helpful:

[Introduction to YapDatabase](https://medium.com/@mark_koslow/introduction-to-yap-database-478d2f18880c)
