### ISSUE TITLE
[Swift] Provide an option to choose the preferred Encoder/Decoder

### ISSUE THREAD

**Issue by mickeyl** [yapstudios/YapDatabase#531]
`YapDatabase.swift`'s `codableSerializer` and `codableDeserializer` explicitly mention the `PropertyListEncoder` / `PropertyListDecoder` which not only creates relatively unefficient byte streams, but is also not available on platforms other than Apple's.

It would be nice to have the option to provide the actual encoder/decoder classes here, so that we could, e.g., use a more efficient `MessagePackEncoder`.

**Comment by gcox** [comment]
@mickeyl If you want to use a different encoder/decoder, you can just call [`registerSerializer`/`registerDeserializer`](https://github.com/yapstudios/YapDatabase/blob/master/YapDatabase/Swift/YapDatabase.swift#L81-L82) and their [metadata counterparts](https://github.com/yapstudios/YapDatabase/blob/master/YapDatabase/Swift/YapDatabase.swift#L99-L100) directly rather than using the helpers.

**Comment by mickeyl** [comment]
@gcox Thanks, yes, I can do that – I just felt it would be more nice to have it in the official API.
