### ISSUE TITLE
Is it possible for an object to belong to more than one group in the same YapDatabaseView?

### ISSUE THREAD

**Issue by BlakeLucchesi** [yapstudios/YapDatabase#57]
My use case is to show a list of contacts with headers for each letter in the alphabet, however at the top I want to show an additional group that shows "Favorite" contacts.  I want to make sure the names under favorites show up there and also under the letter of their first name.  I was wondering how this could be accomplished with YapDatabaseViewGroupingWithObjectBlock when I can only return one NSString for the group the object belongs to.

How would you recommend I go about doing this?

p.s. Thanks for all the great work, I'm really pumped to start working with YapDatabase.

**Comment by corristo** [comment]
@robbiehanson I have a question that is related to this issue.

What is the best approach if groups are dynamic and items could exist in multiple groups? For example, imagine dish and their ingredients, ingredients are groups and dishes are items, and dish could exist in more than one group (since dishes often have more than one ingredient).

I have two possible solutions in mind:
1. Duplicate dish objects for each unique dish-ingredient pair.
2. Create view of ingredients, and manage separate view for each ingredient dynamically.

**Comment by corristo** [comment]
@robbiehanson it seems I've found the answer: https://github.com/yapstudios/YapDatabase/issues/60#issuecomment-38834455

any news regarding mentioned extension?

**Comment by robbiehanson** [comment]
@corristo - I'm assuming you mean a YapDatabaseView that supports having the same object in multiple groups. This is still on my Todo list, but other extensions have priority (YapDatabaseCloudKit which is largely finished, and will be available in v2.6. And YapDatabaseHooks which is currently the next planned extension for v2.7.)

**Comment by corristo** [comment]
@robbiehanson 
>I'm assuming you mean a YapDatabaseView that supports having the same object in multiple groups.

yes, thanks for sharing your plans.

**Comment by jj0b** [comment]
@robbiehanson I just came realized I need a YapDatabaseView that supports having the same object in multiple groups. I've read through the interim solutions and should be able to come up with a workaround, but just curious where adding that functionality to YapDatabaseView is on your Todo list?

**Comment by accatyyc** [comment]
Old issue - but we made a library that allows this (and abstracts away the view updating boilerplate) https://github.com/FootballAddicts/FRZDatabaseViewMapper
